source ~/gps_venv/bin/activate
python3 ~/gps_data.py

source ~/gps_venv/bin/activate
pip3 install -r ~/requirements.txt

sudo nano /etc/systemd/system/gps_data.service

[Unit]
Description=GPS Data Python Script Service
After=network.target

[Service]
ExecStart=/home/mdt/gps_venv/bin/python3 /home/mdt/gps_data.py
WorkingDirectory=/home/mdt
StandardOutput=inherit
StandardError=inherit
Restart=always
User=mdt

[Install]
WantedBy=multi-user.target


sudo chmod +x /home/mdt/gps_data.py

sudo systemctl daemon-reload

sudo systemctl enable gps_data.service

sudo systemctl start gps_data.service

sudo systemctl status gps_data.service

journalctl -u gps_data.service

sudo reboot

